INSERT INTO colors (color) VALUES ('Black');    --c01
INSERT INTO colors (color) VALUES ('Grey');     --c02
INSERT INTO colors (color) VALUES ('Brown');    --c03
INSERT INTO colors (color) VALUES ('Navy');     --c04
INSERT INTO colors (color) VALUES ('Red');      --c05
INSERT INTO colors (color) VALUES ('Blue');     --c06
INSERT INTO colors (color) VALUES ('Beige');    --c07
INSERT INTO colors (color) VALUES ('White');    --c08
INSERT INTO colors (color) VALUES ('Purple');   --c09
INSERT INTO colors (color) VALUES ('Green');    --c10
INSERT INTO colors (color) VALUES ('Yellow');   --c11
INSERT INTO colors (color) VALUES ('Pink');     --c12
INSERT INTO colors (color) VALUES ('Orange');   --c13